blog/blog/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^', include('blog_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog_app/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'blog_app'
urlpatterns = [
    # ex: /
    url(r'^$', views.NotesIndexView.as_view(), name='notes_index'),
    # ex: /note/3
    url(r'^note/(?P<url>[\w-]+)', views.note_details_view, name='note_details'),
    url(r'^tag/(?P<slug>[\w-]+)', views.tag_notes, name='tag_notes'),
    # /about
    url(r'^about/', TemplateView.as_view(template_name="blog_app/about.html")),
    url(r'^resume/',
        TemplateView.as_view(template_name="blog_app/resume.html")),
    url(r'^projects/', TemplateView.as_view(
            template_name="blog_app/projects.html")),
]

blog/blog_app/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from markdown import markdown
from slugify import slugify
from taggit.managers import TaggableManager


class Note(models.Model):
    """
    Attributes:
        title The maximum speed that such a bird can attain.
        body  The locale where these birds congregate to reproduce.
    """
    title = models.CharField(max_length=255, blank=True)
    body = models.TextField(max_length=4000, blank=True, db_index=True)
    body_html = models.TextField(max_length=4000, blank=True)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    tags = TaggableManager(blank=True)
    url = models.CharField(max_length=2000, default=None, blank=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.url = slugify(self.title)
        self.body_html = markdown(self.body)
        super(Note, self).save(*args, **kwargs)

    def __str__(self):
        return '%r %s' % (self.id, self.title)

    def __unicode__(self):
        return self.__str__()

    class Meta:
        ordering = ('-pub_date',)


class AttachedFile(models.Model):
    file = models.FileField(upload_to='%Y/%m/%d/')
    note = models.ForeignKey(Note, on_delete=models.CASCADE,
                             related_name='attaches')

blog/blog_app/views.py
from __future__ import print_function

from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views import generic
from taggit.models import Tag

from .models import Note

class NotesIndexView(generic.ListView):
    template_name = 'blog_app/notes_index.html'
    context_object_name = 'notes'

    def get_queryset(self):
        return Note.objects.filter(pub_date__lte=timezone.now()).order_by(
            '-pub_date')[:50]


def note_details_view(request, url):
    note = get_object_or_404(Note, url=url)
    return render(request, 'blog_app/note_details.html', {'note': note})


def tag_notes(request, slug):
    ctx = {
        'tag': get_object_or_404(Tag, slug=slug),
        'notes': Note.objects.filter(tags__slug=slug),
    }
    return render(request, 'blog_app/notes_index.html', ctx)

blog/blog_app/templates/blog_app/about.html
{% extends "blog_app/base.html" %}

{% block content %}
    About this
{% endblock %}

{% block menu-item %}about{% endblock %}

blog/blog_app/templates/blog_app/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css"
          href="{% static 'blog_app/node_modules/bootstrap/dist/css/bootstrap.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'blog_app/node_modules/font-awesome/css/font-awesome.css' %}"/>
    <link rel="stylesheet" type="text/css" href="
          {% static 'blog_app/css/style.css' %}"/>
    <title>{% block title %}Hello to my blog{% endblock %}</title>
</head>

<body>

<div class="container">
    <div class="row">
        <div class="col-md-11">
            <div id="content">
                {% block content %}{% endblock %}
            </div>
        </div>
        <div class="col-md-1">
            <div id="sidebar" style="position: fixed">
                {% block sidebar %}
                    <div class="list-group">
                        <a href="{% url 'blog_app:notes_index' %}"
                           class="list-group-item" id="menu-main">
                            Notes
                        </a>
                        <a href="/about" class="list-group-item"
                           id="menu-about">About me</a>
                        <a href="/projects" class="list-group-item"
                           id="menu-projects">Projects</a>
                        <a href="/resume" class="list-group-item"
                           id="menu-resume">Resume</a>
                    </div>
                    <script>
                        var element = '{% block menu-item %}main{% endblock %}';
                        document.getElementById('menu-' + element).classList.add('active');
                    </script>
                {% endblock %}
            </div>
        </div>
    </div>
</div>

</body>
</html>

blog/blog_app/templates/blog_app/navbar.html
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'blog_app:notes_index' %}">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Link</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

blog/blog_app/templates/blog_app/note_comments.html
<div id="mc-container"></div>
<script type="text/javascript">
    cackle_widget = window.cackle_widget || [];
    cackle_widget.push({widget: 'Comment', id: 26860});
    (function () {
        var mc = document.createElement('script');
        mc.type = 'text/javascript';
        mc.async = true;
        mc.src = ('https:' == document.location.protocol ? 'https' : 'http') + '://cackle.me/widget.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(mc, s.nextSibling);
    })();
</script>
<a id="mc-link" href="http://cackle.me">Комментарии для сайта <b
        style="color:#4FA3DA">Cackl</b><b style="color:#F65077">e</b></a>

blog/blog_app/templates/blog_app/note_details.html
{% extends "blog_app/base.html" %}
{% load static %}

{% block content %}

<h3>{{ note.title }}</h3>
<span>{{ note.body_html | safe }}</span>
{{ note.pub_date }}

{% if note.image %}
    <img src="{{ note.image.url }}" alt="">
{% endif %}

{% for tag in note.tags.all %}
    <a href="{% url 'blog_app:tag_notes' tag.slug %}">{{ tag.name }}</a>
{% endfor %}

{% include 'blog_app/note_comments.html' %}

{% endblock %}

blog/blog_app/templates/blog_app/notes_index.html
{% extends "blog_app/base.html" %}

{% block content %}
    {% if tag %}
        <h2>
            Tag: {{ tag.name }}
        </h2>
    {% endif %}
    {% for note in notes %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <a href="{% url 'blog_app:note_details' note.url %}">
                    <span class="panel-title">
                        {{ note.title }}
                    </span>
                </a>
            </div>
            <div class="panel-body">
                {{ note.body_html | safe }}
            </div>
            <div class="panel-footer">
                {{ note.pub_date | date:"Y.m.d H:i:s" }}
                <span class="pull-right">
                    {% for tag in note.tags.all %}
                        <a href={% url 'blog_app:tag_notes' tag.slug %}
                        >{{ tag.name }}</a>
                    {% endfor %}
                </span>
            </div>
        </div>
    {% endfor %}
{% endblock %}

blog/blog_app/templates/blog_app/projects.html
{% extends "blog_app/base.html" %}

{% block content %}
    Projects page
{% endblock %}

{% block menu-item %}projects{% endblock %}

blog/blog_app/templates/blog_app/resume.html
{% extends "blog_app/base.html" %}

{% block content %}
    Background page
{% endblock %}

{% block menu-item %}resume{% endblock %}